### ISSUE TITLE
paginate search results

### ISSUE THREAD

**Issue by amilajack** [amilajack/tide#169]
## Tasks
- [x] 1. create `Paginate` component (use boilerplate below as starting point)
- [x] 2. take a `page` prop to specify current page
- [x] 3. take a `totalResults` prop
- [x] 4. use limit sound list results to max of 5 by default, 
- [x] 5. write a function that takes the number of results, the num of results per page, and returns the number of pages
- [x] 6. incorporate what you built with [tailwind's example](https://tailwindui.com/components/application-ui/navigation/pagination)
- [ ] 7. as a nice touch, rename `SoundListContainer`'s `tracks` prop to `sounds` (very inconsistent naming right now)

## Idea Usage

```jsx
function onPageClick(page) {
  freesound.search('foo', { page, limit: 5 })
}

<Paginate limit={5} page={1} totalResults={100} onPageClick={onPageClick}>
  <SoundListContainer sounds={mySounds} etc.../>
</Paginate>
```

* `SoundListContainer` should still be responsible for listing and playing sounds
* `Paginate` should be responsible for keeping track of the current page, rendering the pagination buttons (next, prev, 1, 2, 3, etc).

## Examples
* https://github.com/AdeleD/react-paginate
* https://react-bootstrap.github.io/components/pagination/

## Watch
https://youtu.be/IYCa1F-OWmk

## Readings:
* https://ihsavru.medium.com/react-paginate-implementing-pagination-in-react-f199625a5c8e
* https://www.seoptimer.com/blog/what-is-pagination/
* https://agentestudio.com/blog/pagination-design-examples-and-best-practices

## Boilerplate
```ts
function Paginate({ children, page, limit, totalResults }) {
  const pageCount = determinePageCount(limit, totalResults);
  const pages = []
  for (...) pages.push(i);
  return (
    <div>
      {children}
      <button onClick={...}>Prev</button>
      pages.map(e => <div onClick={...}>{e}</div>)
      <button onClick={...}>Next</button>
    </div>
  )
}
```

**Comment by hamirmahal** [comment]
In which places do we want to see the pagination bar?

If we want to see it in multiple places, like on tag pages and search result pages, we may want to create a reusable `<PaginationBar />` component.

**Comment by hamirmahal** [comment]
> * [ ]  limit sound list results to max of 5

Do we always want a maximum of 5 results? For example, should the "Pack" and "Similar" `<SoundListContainer />` components on a sound's page also have at most 5 results?

**Comment by amilajack** [comment]
Good question. This should be configurable via a prop. Default prop value should be 5 for now. We can change it later if we want.

**Comment by amilajack** [comment]
@hamirmahal added some more context to the solution. I recommend playing around with https://github.com/AdeleD/react-paginate and try seeing if you can pass tailwind classes as props to give it consistent styling with the result of tide.

**Comment by amilajack** [comment]
Correct, all sound list should be able to be used inside of a `Pagination` component. Note that from the ideal usage section in the ticket description, the `Paginate` component should know nothing about the `SoundListContainer`

**Comment by hamirmahal** [comment]
> I recommend playing around with https://github.com/AdeleD/react-paginate and try seeing if you can pass tailwind classes as props to give it consistent styling with the result of tide. Don't worry about data fetching and updating the SoundListContainer initially. I recommend focusing on the component aspect initially.

Are we sure we don't just want to use Tailwind's pre-built pagination element?

> * [ ]  implement pagination UI (See https://tailwindui.com/components/application-ui/navigation/pagination)

I made a bit of progress with it a few weeks ago. The issue is just that the whole pagination element is in `SearchResults.js`. I was trying to pinpoint exactly where the pagination element should be to figure out how to refactor things correctly.

![Screen Shot 2020-12-15 at 9 11 24 PM](https://user-images.githubusercontent.com/43425812/102307801-180ae980-3f1a-11eb-9bcf-8ff0703aba47.png)

![Screen Shot 2020-12-15 at 9 11 38 PM](https://user-images.githubusercontent.com/43425812/102307814-20632480-3f1a-11eb-9c60-5f866ebe46ad.png)

![Screen Shot 2020-12-15 at 9 11 54 PM](https://user-images.githubusercontent.com/43425812/102307835-2b1db980-3f1a-11eb-9768-3b68b88173bc.png)

**Comment by amilajack** [comment]
@hamirmahal good point, i think if its not too hard, we should use the tailwind template if possible

**Comment by hamirmahal** [comment]
Okay, I'll play around with it. Thanks for the additional information!

**Comment by hamirmahal** [comment]
> * [ ]  4. use **limit** sound list results to max of 5 by default,
> ## Idea Usage
> ```js-jsx
> ...
>   freesound.search('foo', { page, **limit**: 5 })
> ...
> <Paginate **limit**={5} ...
> ```
> ## Boilerplate
> ```ts
> function Paginate({ children, page, **limit**, totalResults }) {
>   const pageCount = determinePageCount(**limit**, totalResults);
>   ...
> ```

Can we call `limit` `numberOfResultsPerPage` instead? It's more verbose, but I think it's more self-documenting, especially as I'm filling in values and expressions that depend on `limit`, or `numberOfResultsPerPage`.
